# Generated by Django 5.0.6 on 2024-07-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='alt',
            field=models.CharField(default=False, max_length=255, verbose_name='Texte alternatif'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ManyToManyField(null=True, to='blog.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
