# Generated by Django 5.0.6 on 2024-07-05 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Auteur')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('status', models.CharField(choices=[('visible', 'visible'), ('hidden', 'hidden'), ('moderated', 'moderated')], default='visible', max_length=20, verbose_name='Statut')),
                ('moderation_text', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost', verbose_name='Articles')),
            ],
            options={
                'verbose_name': 'Commentaire',
            },
        ),
    ]
