# Generated by Django 5.0.6 on 2024-07-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='author_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='content_comment',
        ),
    ]
