# Generated by Django 5.0.6 on 2024-07-22 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_author_comment_author_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_answer', models.CharField(max_length=100, verbose_name='Auteur')),
                ('content_answer', models.TextField(verbose_name='Contenu')),
                ('status', models.CharField(choices=[('visible', 'visible'), ('hidden', 'hidden'), ('moderated', 'moderated')], default='visible', max_length=20, verbose_name='Statut')),
                ('moderation_text_answer', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='blog.comment', verbose_name='Commentaire')),
            ],
            options={
                'verbose_name': 'Réponses',
            },
        ),
    ]
