# Generated by Django 5.0.7 on 2024-08-01 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_commentanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentanswer',
            options={'verbose_name': 'Réponse'},
        ),
        migrations.AlterField(
            model_name='commentanswer',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='blog.comment', verbose_name='Commentaire'),
        ),
    ]
