# Generated by Django 5.1 on 2024-08-29 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpost_created_on_alter_blogpost_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Date de publication'),
        ),
    ]
