# Generated by Django 5.1 on 2025-03-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogpost_created_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentAnswer',
            new_name='Reply',
        ),
    ]
