# Generated by Django 5.1 on 2025-03-30 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_author_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_comment',
            field=models.CharField(max_length=100, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_comment',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost', verbose_name='Articles'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('visible', 'visible'), ('hidden', 'hidden'), ('moderated', 'moderated')], default='visible', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='author_answer',
            field=models.CharField(max_length=100, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content_answer',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='status',
            field=models.CharField(choices=[('visible', 'visible'), ('hidden', 'hidden'), ('moderated', 'moderated')], default='visible', max_length=20, verbose_name='Statut'),
        ),
    ]
