# Generated by Django 5.0.6 on 2024-07-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_on', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('thumbnail', models.ImageField(blank=True, upload_to='gallery')),
                ('alt', models.CharField(default=False, max_length=30, verbose_name='Texte alternatif')),
            ],
            options={
                'verbose_name': 'Image',
                'ordering': ['-created_on'],
            },
        ),
    ]
