# Generated by Django 5.0.6 on 2024-07-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='content',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contenu'),
        ),
    ]
