# Generated by Django 5.0.6 on 2024-07-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallery_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='alt',
            field=models.CharField(default=False, max_length=255, verbose_name='Texte alternatif'),
        ),
    ]
