# Generated by Django 5.1 on 2024-08-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallery_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
