# Generated by Django 5.1 on 2024-08-29 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Date de publication'),
        ),
    ]
