# Generated by Django 5.1 on 2024-08-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reels',
            name='title',
            field=models.CharField(max_length=40, unique=True, verbose_name='Titre'),
        ),
    ]
