# Generated by Django 5.1 on 2024-08-29 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reel', '0002_alter_reels_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reels',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Date de publication'),
        ),
    ]
